trigger:
- main

variables:
  azureSubscription: 'VisualStudio'
  vmImageName: 'ubuntu-latest'
  imageRepository: 'wordpress'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:

    - task: AzureCLI@2
      displayName: Az login
      name: acr_name
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: |
          $query="[?ends_with(name, 'sbx')].loginServer" 
          $containerRegistry = az acr list --query $query --output tsv
          echo "##vso[task.setvariable variable=containerRegistry]$containerRegistry"

    - task: AzureCLI@2
      displayName: Build docker image
      name: docker_build
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo $(containerRegistry)
          docker build -f Dockerfile -t $(containerRegistry)/$(imageRepository):$(tag) .