trigger:
- main

variables:
- name: subscription
  value: 'AzureCloud'
- name: imageRepository
  value: 'wordpress'
- name: tag
  value: '$(Build.BuildId)'

pool:
    vmImage: ubuntu-latest


steps:
  - task: AzureCLI@2
    displayName: Get ACR name
    inputs:
      azureSubscription: $(subscription)
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'
      inlineScript: |
        $query="[?ends_with(name, 'dev')].loginServer" 
        $containerRegistry = az acr list --query $query --output tsv
        echo "##vso[task.setvariable variable=containerRegistry]$containerRegistry"

  - task: AzureCLI@2
    displayName: Build Docker Image
    inputs:
      azureSubscription: $(subscription)
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'
      inlineScript: "docker build -f Dockerfile -t $(containerRegistry)/$(imageRepository):v$(tag) ."

  - task: AzureCLI@2
    displayName: Login to ACR
    inputs:
      azureSubscription: $(subscription)
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'
      inlineScript: | 
        $ip_address = curl http://ipv4.icanhazip.com
        $query="[?ends_with(name, 'dev')].name"
        $registry = az acr list --query $query --output tsv
        az acr network-rule add --name $registry --ip-address $ip_address
        $password = az acr credential show --name $registry --query passwords[0].value
        $query="[?ends_with(name, 'dev')].loginServer" 
        $containerRegistry = az acr list --query $query --output tsv
        docker login $containerRegistry --username $registry --password $password

  - task: AzureCLI@2
    displayName: Push Docker Image
    inputs:
      azureSubscription: $(subscription)
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'
      inlineScript: | 
        docker push $(containerRegistry)/$(imageRepository):v$(tag)